name: Dep reqs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '0 5 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  minimal-deps:
    # Build and test with the oldest possible versions of deps. This helps ensure the semver requirements for deps
    # are OK.
    runs-on: ubuntu-latest
    container:
      image: rust:1.65.0
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
    - name: Set up nightly
      run: |
        rustup install nightly-2023-08-06
        rustup default nightly-2023-08-06
    - name: Remove Cargo.lock
      run: rm Cargo.lock
    - name: Build
      run: cargo build --all-features -Zminimal-versions --verbose
    - name: Run tests
      run: cargo test --all-features --workspace -Zminimal-versions --verbose
  maximal-deps:
    # Build and test with the newest possible versions of deps. This helps ensure the semver requirements for deps
    # are OK.
    runs-on: ubuntu-latest
    container:
      image: rust:stable
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
    - name: Update Cargo.lock
      run: cargo update
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests
      run: cargo test --all-features --workspace --verbose
